[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"

[etherscan]
arc_testnet = { api_url = "https://api-testnet.arcscan.app/api", api_key = "${ARCSCAN_API_KEY}" }

